use company;

select * from customer_sb
limit 10;
RENAME TABLE `customer_shopping_behavior` TO customer_SB;

-- 1.wt is the total revenue generated by male and female customers?
select sum(purchase_amount),gender as revenuse from customer_SB
group by gender;

-- 2.which customers used a disocunt but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer_sb
where discount_applied="yes" and purchase_amount>
(select avg(purchase_amount) from customer_sb
where discount_applied="yes");

-- 3. which are the top 5 products with the highest average review rating (so they can increase the price n keep them as premium products)
select item_purchased,round(avg(review_rating),2)as avg_rating from customer_sb
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- 4. compare the average purchase amount between standard and express shipping (if express is more than company should invest more on express for faster delivery)
select avg(purchase_amount),shipping_type from customer_sb
where shipping_type in("express","standard")
group by shipping_type;

-- 5. do subscribed customers spend more? compare avg spend and total revenue on subscribers and non-subscribers
select avg(purchase_amount) avg_purchase,sum(purchase_amount) revenue,subscription_status,count(customer_id) count from customer_sb
where subscription_status in("yes","no")
group by subscription_status
order by revenue, avg_purchase desc;

-- 6. which 5 products have the highest percentage of purchase with of discount appiled
select item_purchased,round(sum(case when discount_applied='yes' then 1 else 0 end )/count(*)*100,2) as discount from customer_sb
group by item_purchased
order by discount desc
limit 5;

-- 7. segment customers into new,returing and loyal based on their total no of previous purchases and show the count of each segment

 with customer_type as
 (select case when previous_purchases=1 then "new" 
              when previous_purchases  between 2 and 10  then "returning" 
              else "loyal" end customer_segment
from customer_sb) 
select customer_segment,count(*) from customer_type
group by customer_segment;
-- 8. what are the top 3 most purchased products in each category
with top_items as
(select item_purchased,category, count(customer_id) total_orders,
row_number()over(partition by category order by count(customer_id) desc) as product_rank from customer_sb
group by category,item_purchased) 
select product_rank,item_purchased,category,total_orders from top_items
where product_rank<=3;

 -- 9. Are customers who are repeat buyer(cus with more than 5 purchaser) also likely to subscribe?
select subscription_status,count(customer_id) from customer_sb
where previous_purchases>=5
group by subscription_status;

-- 10. what is the revenue contribution of each age_group?  

select sum(purchase_amount) revenue,age_group
from customer_sb
group by age_group
order by revenue desc;

 
 
 

